// generated by Fast Light User Interface Designer (fluid) version 3.0000

#ifndef gui_h
#define gui_h
#include <fltk3/run.h>
#include <fltk3/Group.h>
#include <fltk3/Button.h>
extern void leftcb(fltk3::Button*, void*);
extern void rightcb(fltk3::Button*, void*);
extern void matchcb(fltk3::Button*, void*);
extern void exitcb(fltk3::Button*, void*);
extern void vizcb(fltk3::Button*, void*);
extern void mndcb(fltk3::Button*, void*);
#include <fltk3/Box.h>
#include <fltk3/CheckButton.h>

class UserInterface : public fltk3::Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
  fltk3::CheckButton *feature_match_rb;
  fltk3::CheckButton *optical_flow_rb;
  fltk3::CheckButton *dense_of_rb;
  fltk3::CheckButton *horiz_disparity_rb;
};
#endif
